# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  mg-up:
    dotenv: [".env"]
    cmds:
      - migrate -path db/migration -database $POSTGRES_URL --verbose up
  mg-down:
    dotenv: [".env"]
    cmds:
      - migrate -path db/migration -database $POSTGRES_URL --verbose down
  build:
    cmds:
      - sqlc generate
      - go build
  dev:
    cmds:
      - sqlc generate
      - air .
