// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateAbilities implements pgx.CopyFromSource.
type iteratorForCreateAbilities struct {
	rows                 []AbilityEnum
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAbilities) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAbilities) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateAbilities) Err() error {
	return nil
}

func (q *Queries) CreateAbilities(ctx context.Context, name []AbilityEnum) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ability"}, []string{"name"}, &iteratorForCreateAbilities{rows: name})
}
